name: Remote Dispatch Action Responder
 
on: [repository_dispatch]
 
jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Subida al repositorio
        run: |
          sudo apt-get install reprepro dpkg-sig
      - name: Subida al repositorio
        run: |
          gpg --import pub.key
          gpg --import private.key
          gpg -k
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.VERSIONDEB }}'"
          ls -l
          ./upload.sh ${{ github.event.client_payload.VERSIONDEB }}
          git config --local user.email "dcf.maker@gmail.com"
          git config --local user.name "dcf-maker"
          git commit -m "Add changes ${{ github.event.client_payload.VERSIONDEB }}" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          
